services:
  mariadb:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal

  nextcloud:
    image: nextcloud:28-apache
    container_name: nextcloud-app
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
    volumes:
      - ./nextcloud:/var/www/html
      # - nextcloud-html:/var/www/html
      - ./nextcloud/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - internal
      - web

  nginx:
    image: nginx:stable-alpine
    container_name: nextcloud-nginx
    restart: always
    depends_on:
      - nextcloud
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs

    ports:
      - '80:80'
      - '443:443'
    networks:
      - web
      - internal

  # tailscale:
  #   build: ./tailscale
  #   container_name: nextcloud-tailscale
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   network_mode: 'host'
  #   volumes:
  #     - /dev/net/tun:/dev/net/tun
  #     - tailscale-var:/var/lib/tailscale
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTHKEY}
  #     - TS_EXTRA_ARGS=--advertise-tags=tag:nextcloud
  #   restart: always

networks:
  web:
  internal:

volumes:
  db-data:
  nextcloud-html:
  # tailscale-var:
